name: Feature Request
description: No, I won't add more notes to the engine, ask someone to PR it.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
